services:
  flask-app:
    build: ./app  # Assuming the Dockerfile is in the app folder
    container_name: flaskapp
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app 
    environment:
      FLASK_ENV: development
      POSTGRES_DB: traffic_db
      POSTGRES_USER: traffic_admin
      POSTGRES_PASSWORD: traffic_pass
    depends_on:
      - postgres
      - kafka
  

  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: traffic_db
      POSTGRES_USER: traffic_admin
      POSTGRES_PASSWORD: traffic_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data



  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  namenode:
    container_name: namenode
    image: apache/hadoop:3  # Use the correct image
    hostname: namenode
    command: ["hdfs", "namenode"]
    user: root
    ports:
      - 9870:9870  # NameNode Web UI
      - 9000:9000  # HDFS transfer port
    volumes:
      - ./namenode:/tmp/hadoop-root/dfs/name  # Ensure the directory is mounted
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml  # Mount config files
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"  # Ensure the NameNode directory

    networks:
      - hadoop-networks
      
  datanode:
    container_name: datanode
    image: apache/hadoop:3
    command: ["hdfs", "datanode"]
    user: root
    ports:
      - 9864:9864  # DataNode Web UI
    volumes:
      - ./datanode:/tmp/hadoop-root/dfs/data  # Ensure the directory is mounted
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    networks:
      - hadoop-network

  spark:
    container_name: spark
    image: bitnami/spark:latest
    ports:
      - "8080:8080"  # Spark UI
      - "7077:7077"  # Spark master port
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark-data:/opt/spark/data
    depends_on:
      - kafka

  airflow:
    container_name: airflow
    image: apache/airflow:latest
    ports:
      - "8081:8081"
    environment:
      LOAD_EX: "y"
      EXECUTOR: "LocalExecutor"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
    depends_on:
      - postgres

networks:
  hadoop-network:
    driver: bridge

  kafka_network:
    driver: bridge

volumes:
  postgres_data: {}
