global:
  scrape_interval: 5s  # Adjust based on your needs

scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['statsd-exporter:9102']  # This is the StatsD exporter

  - job_name: 'prometheus'  # For Prometheus itself.
    static_configs:
      - targets: ['35.240.185.84:9090']

  - job_name: 'node_exporter'  # Scrape Node Exporter.
    static_configs:
      - targets: ['35.240.185.84:9100']  # Replace <vm-ip> with your VM IP.

  - job_name: 'cadvisor'  # Scrape cAdvisor metrics.
    static_configs:
      - targets: ['35.240.185.84:8081']

remote_write:
  - url: "https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push"
    basic_auth:
        username : "1895912"
        password : "glc_eyJvIjoiMTI3MDgzOCIsIm4iOiJzdGFjay0xMDg5NDYwLWhtLXdyaXRlLWZ5cCIsImsiOiJzWDU5S1I4MzBLQVc3YkczZHI3dDQyS3UiLCJtIjp7InIiOiJwcm9kLWFwLXNvdXRoZWFzdC0xIn19"
