global:
  scrape_interval: 5s  # Adjust based on your needs

scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['statsd-exporter:9102']  # This is the StatsD exporter
